name: Documentation
description: Report documentation issues or request improvements
labels: [documentation]
body:
  - type: markdown
    attributes:
      value: |
        ## Documentation Issue
        Help us improve our documentation!

  - type: dropdown
    id: type
    attributes:
      label: Issue Type
      description: What type of documentation issue is this?
      options:
        - Missing documentation
        - Incorrect information
        - Unclear or confusing
        - Outdated content
        - Broken links
        - Typo or grammar
        - Improvement suggestion
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Document Location
      description: Which file or page has the issue?
      placeholder: e.g., docs/guides/deployment.md or README.md
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the documentation issue
      placeholder: What's wrong or missing?
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How would you improve this documentation?
      placeholder: Your suggested changes or additions

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any additional context that might help
      placeholder: Screenshots, links, related docs
