import {
  AlertCircle,
  AlertTriangle,
  Award,
  BadgeCheck,
  Banknote,
  BarChart3,
  Battery,
  Beef,
  Beer,
  Bitcoin,
  Calendar,
  Candy,
  Car,
  CheckCircle,
  Cigarette,
  CigaretteOff,
  Clipboard,
  Clock,
  Cloud,
  Coffee,
  Compass,
  Copy,
  CreditCard,
  DollarSign,
  Download,
  Droplets,
  ExternalLink,
  Flag,
  Gift,
  Globe,
  Grid3x3,
  Headphones,
  Heart,
  HelpCircle,
  Home,
  Info,
  Languages,
  Laptop,
  LayoutDashboard,
  Leaf,
  List,
  Lock,
  Mail,
  Map,
  MapPin,
  Mic,
  Monitor,
  Moon,
  Navigation,
  Package,
  Palette,
  Phone,
  PieChart,
  Pizza,
  Printer,
  Radio,
  Receipt,
  Search,
  Send,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Star,
  Sun,
  Tag,
  Thermometer,
  Ticket,
  Trash2,
  TrendingUp,
  Truck,
  Tv,
  Unlock,
  Upload,
  User,
  Users,
  Utensils,
  UtensilsCrossed,
  Volume2,
  Wheelchair,
  Wifi,
  Wine,
  XCircle,
  Zap,
} from 'lucide-react';

const ICON_MAP = {
  'alert-circle': <AlertCircle size={20} />,
  'alert-triangle': <AlertTriangle size={20} />,
  award: <Award size={20} />,
  'badge-check': <BadgeCheck size={20} />,
  banknote: <Banknote size={20} />,
  'bar-chart': <BarChart3 size={20} />,
  battery: <Battery size={20} />,
  beef: <Beef size={20} />,
  beer: <Beer size={20} />,
  bitcoin: <Bitcoin size={20} />,
  calendar: <Calendar size={20} />,
  candy: <Candy size={20} />,
  car: <Car size={20} />,
  'check-circle': <CheckCircle size={20} />,
  cigarette: <Cigarette size={20} />,
  'cigarette-off': <CigaretteOff size={20} />,
  clipboard: <Clipboard size={20} />,
  clock: <Clock size={20} />,
  cloud: <Cloud size={20} />,
  coffee: <Coffee size={20} />,
  compass: <Compass size={20} />,
  copy: <Copy size={20} />,
  'credit-card': <CreditCard size={20} />,
  'dollar-sign': <DollarSign size={20} />,
  download: <Download size={20} />,
  droplets: <Droplets size={20} />,
  'external-link': <ExternalLink size={20} />,
  flag: <Flag size={20} />,
  gift: <Gift size={20} />,
  globe: <Globe size={20} />,
  grid: <Grid3x3 size={20} />,
  headphones: <Headphones size={20} />,
  heart: <Heart size={20} />,
  'help-circle': <HelpCircle size={20} />,
  home: <Home size={20} />,
  info: <Info size={20} />,
  languages: <Languages size={20} />,
  laptop: <Laptop size={20} />,
  'layout-dashboard': <LayoutDashboard size={20} />,
  leaf: <Leaf size={20} />,
  list: <List size={20} />,
  lock: <Lock size={20} />,
  mail: <Mail size={20} />,
  map: <Map size={20} />,
  'map-pin': <MapPin size={20} />,
  mic: <Mic size={20} />,
  monitor: <Monitor size={20} />,
  moon: <Moon size={20} />,
  navigation: <Navigation size={20} />,
  package: <Package size={20} />,
  palette: <Palette size={20} />,
  phone: <Phone size={20} />,
  'pie-chart': <PieChart size={20} />,
  pizza: <Pizza size={20} />,
  printer: <Printer size={20} />,
  radio: <Radio size={20} />,
  receipt: <Receipt size={20} />,
  search: <Search size={20} />,
  send: <Send size={20} />,
  settings: <Settings size={20} />,
  'share-2': <Share2 size={20} />,
  shield: <Shield size={20} />,
  'shield-check': <ShieldCheck size={20} />,
  'shopping-bag': <ShoppingBag size={20} />,
  'shopping-basket': <ShoppingBasket size={20} />,
  'shopping-cart': <ShoppingCart size={20} />,
  smartphone: <Smartphone size={20} />,
  sparkles: <Sparkles size={20} />,
  star: <Star size={20} />,
  sun: <Sun size={20} />,
  tag: <Tag size={20} />,
  thermometer: <Thermometer size={20} />,
  ticket: <Ticket size={20} />,
  'trash-2': <Trash2 size={20} />,
  'trending-up': <TrendingUp size={20} />,
  truck: <Truck size={20} />,
  tv: <Tv size={20} />,
  unlock: <Unlock size={20} />,
  upload: <Upload size={20} />,
  user: <User size={20} />,
  users: <Users size={20} />,
  utensils: <Utensils size={20} />,
  'utensils-crossed': <UtensilsCrossed size={20} />,
  'volume-2': <Volume2 size={20} />,
  wheelchair: <Wheelchair size={20} />,
  wifi: <Wifi size={20} />,
  wine: <Wine size={20} />,
  'x-circle': <XCircle size={20} />,
  zap: <Zap size={20} />,
};

const normalizeKey = (key) => {
  if (!key || typeof key !== 'string') return key;
  // Normalize: dashes→underscores, trim
  const normalized = key.trim().toLowerCase().replace(/-/g, '_');
  return normalized;
};

const ICON_MAP_NORMALIZED = {};
for (const [k, v] of Object.entries(ICON_MAP)) {
  ICON_MAP_NORMALIZED[normalizeKey(k)] = v;
}

export const resolveServiceIcon = (icon) => {
  if (!icon) return null;
  if (typeof icon !== 'string') return icon;
  const key = normalizeKey(icon);
  return ICON_MAP_NORMALIZED[key] ?? null;
};
